// Package globalconfig loads the dbpod-wide configuration file
// ($DBPOD_HOME/config.yaml): proxy settings, named sources and their
// credentials.
package globalconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/dbpod-io/dbpod/internal/contract"
	"github.com/dbpod-io/dbpod/internal/fetch"
	"github.com/dbpod-io/dbpod/internal/project"
	"gopkg.in/yaml.v3"
)

// Config is the global configuration document.
type Config struct {
	// Proxy is the global default, applied to every provider that does not
	// declare its own override.
	Proxy ProxyConfig `yaml:"proxy"`

	// Providers holds per-engine settings: sources (with inline auth), an
	// optional proxy override, and — for config-declared engines — the
	// engine description itself (family/profile/index_url/download).
	Providers map[string]ProviderConfig `yaml:"providers"`
}

// ProxyConfig is the transport-level proxy configuration.
type ProxyConfig struct {
	HTTP    string   `yaml:"http"`
	Socks5  string   `yaml:"socks5"`
	NoProxy []string `yaml:"no_proxy"`
}

// ProviderConfig is the per-engine settings block of the global config
// (sources with inline auth, proxy override).
type ProviderConfig struct {
	DefaultSource string            `yaml:"default_source,omitempty"`
	Sources       map[string]Source `yaml:"sources,omitempty"`
	Proxy         *ProxyConfig      `yaml:"proxy,omitempty"`
}

// EngineManifest is a config-declared engine: one flat YAML document
// (dropped into $DBPOD_HOME/engines.d/<name>.yaml) that describes the
// engine completely — which lifecycle machinery to reuse, its lifecycle
// commands, where its version index lives, and how package URLs are built.
//
// It is an ARTIFACT owned by the engine project: users never edit it (a
// "do not edit" header says so), `registry update` replaces it wholesale
// when the upstream revision is newer. Deployment-specific settings
// (mirrors, sources, proxy) live in the user layer — the providers.<name>
// block of this file.
type EngineManifest struct {
	// Name is the engine identifier ("mariadb").
	Name string `yaml:"name"`

	// Family selects the lifecycle machinery to reuse ("mysql").
	Family string `yaml:"family"`

	// Version is the manifest revision, bumped by the engine project when
	// the manifest content changes. `registry update` compares the local
	// version against the source's and refreshes when the source is newer.
	Version string `yaml:"version,omitempty"` // content version, major.minor ("0.1" initial); bumped by the engine project

	// Source records where the manifest was registered from (filled by
	// `registry add` for remote sources); `registry update` re-fetches it
	// from here.
	Source string `yaml:"source,omitempty"`

	// IndexURL points at the engine's version index (native metadata.Index
	// JSON, generated by the engine's own tooling). Optional: exact
	// versions install from the download templates alone.
	IndexURL string `yaml:"index_url,omitempty"`

	// Download describes how to build package URLs per platform.
	Download *DownloadSpec `yaml:"download,omitempty"`

	// EngineProfile fields inlined: the five lifecycle command templates
	// (init/start/client/exec/shutdown) and the server config content.
	contract.EngineProfile `yaml:",inline"`
}

// DownloadSpec declares the package layout of a config-declared engine:
// per-platform URL templates ({version}/{series} placeholders, relative to the
// configured source base) and the checksums file published alongside
// each archive.
type DownloadSpec struct {
	Targets map[string]DownloadTarget `yaml:"targets"` // key: "<goos>/<goarch>"
	// Checksums is the sums file name in the archive directory (e.g.
	// sha256sums.txt); its "<hash>  <filename>" lines provide integrity.
	Checksums string `yaml:"checksums,omitempty"`
}

// DownloadTarget is one platform's package URL template.
type DownloadTarget struct {
	URL  string `yaml:"url"`  // may contain {version}; relative or absolute
	Kind string `yaml:"kind"` // tar.gz | tar.xz | zip
}

// Source is a named data source: metadata/base URLs plus inline
// authentication (secrets preferably via env references).
type Source struct {
	Index string     `yaml:"index"`
	Base  string     `yaml:"base"`
	Auth  SourceAuth `yaml:"auth,omitempty"`
}

// SourceAuth is the inline authentication of a source.
type SourceAuth struct {
	User        string `yaml:"user,omitempty"`
	PasswordEnv string `yaml:"password_env,omitempty"`
	Password    string `yaml:"password,omitempty"`
}

// Path returns the global config file location.
func Path() (string, error) {
	h, err := project.HomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(h, "config.yaml"), nil
}

// EnginesDir returns the drop-in directory for engine manifests
// (<DBPOD_HOME>/engines.d).
func EnginesDir() (string, error) {
	h, err := project.HomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(h, "engines.d"), nil
}

// ManifestError is a per-file manifest problem: one broken manifest must
// not take down the others.
type ManifestError struct {
	File string
	Err  error
}

func (e *ManifestError) Error() string { return e.File + ": " + e.Err.Error() }

// LoadEngines reads every engine manifest from EnginesDir. A missing
// directory yields no manifests; per-file problems (unparsable yaml,
// missing name) are returned separately so the remaining manifests load.
func LoadEngines() (manifests []EngineManifest, errs []*ManifestError) {
	dir, err := EnginesDir()
	if err != nil {
		return nil, []*ManifestError{{File: dir, Err: err}}
	}
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, []*ManifestError{{File: dir, Err: err}}
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || (!strings.HasSuffix(name, ".yaml") && !strings.HasSuffix(name, ".yml")) {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			errs = append(errs, &ManifestError{File: name, Err: err})
			continue
		}
		var m EngineManifest
		if err := yaml.Unmarshal(data, &m); err != nil {
			errs = append(errs, &ManifestError{File: name, Err: fmt.Errorf("parse: %w", err)})
			continue
		}
		if m.Name == "" {
			errs = append(errs, &ManifestError{File: name, Err: fmt.Errorf("engine manifest has no name")})
			continue
		}
		manifests = append(manifests, m)
	}
	return manifests, errs
}

// ParseManifest decodes a single engine manifest document (as written by
// registry add).
func ParseManifest(data []byte) (*EngineManifest, error) {
	var m EngineManifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parse: %w", err)
	}
	if m.Name == "" {
		return nil, fmt.Errorf("engine manifest has no name")
	}
	return &m, nil
}

// Load reads the global config; a missing file yields the zero Config.
func Load() (*Config, error) {
	path, err := Path()
	if err != nil {
		return nil, err
	}
	cfg := &Config{}
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return cfg, nil
	}
	if err != nil {
		return nil, err
	}
	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return cfg, nil
}

// Apply pushes the loaded settings into the fetch layer: the global
// default proxy, plus per-provider clients for providers that declare
// their own proxy override.
func (c *Config) Apply() {
	fetch.SetProxy(fetch.Proxy{
		HTTP:    c.Proxy.HTTP,
		Socks5:  c.Proxy.Socks5,
		NoProxy: c.Proxy.NoProxy,
	})
	for name, pc := range c.Providers {
		if pc.Proxy != nil && (pc.Proxy.HTTP != "" || pc.Proxy.Socks5 != "") {
			fetch.RegisterClient(name, fetch.NewClient(fetch.Proxy{
				HTTP:   pc.Proxy.HTTP,
				Socks5: pc.Proxy.Socks5,
			}))
		}
	}
}
