// Package mongodb implements the engine.Engine interface for MongoDB via
// the manifest-driven lifecycle: mongod self-initializes its data
// directory (no init step), configuration is a YAML file, and the
// client/admin tool is mongosh (shipped alongside the server through the
// download plan's dependency mechanism).
package mongodb

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"time"

	"github.com/dbpod-io/dbpod/internal/engine"
)

func init() {
	engine.Register(New())
}

// Family invariants of MongoDB distributions.
const (
	configFile = "mongod.conf"
)

// dataMarkers identify an initialized data directory (WiredTiger
// metadata, written by mongod on first start).
var dataMarkers = []string{"WiredTiger.wt", "mongod.lock"}

// Engine implements engine.Engine for MongoDB.
type Engine struct{}

// New builds the engine.
func New() *Engine { return &Engine{} }

func (e *Engine) Name() string { return "mongodb" }

// BinaryNames returns the server and client binaries. MongoDB ships no
// dedicated admin tool: graceful shutdown goes through mongosh.
func (e *Engine) BinaryNames() (server, client, admin string) {
	return "mongod", "mongosh", "mongosh"
}

// ExecPaths: the distribution ships its binaries in bin/.
func (e *Engine) ExecPaths() []string { return []string{"bin"} }

// DataDirInitialized checks for WiredTiger metadata in the datadir:
// mongod self-initializes on first start, so an empty directory is simply
// a fresh instance.
func (e *Engine) DataDirInitialized(opts engine.Options) bool {
	return engine.LooksInitialized(filepath.Join(opts.DataDir, "data"), dataMarkers...)
}

// InitDataDir prepares the instance directories and renders mongod.conf
// (mongod itself initializes the data store on first start — there is no
// separate init step). The conf must exist before the first start.
func (e *Engine) InitDataDir(opts engine.Options) error {
	if _, err := e.WriteConfig(opts); err != nil {
		return err
	}
	return nil
}

// ServerArgs builds the mongod command line.
func (e *Engine) ServerArgs(opts engine.Options) []string {
	return []string{"--config", e.configPath(opts)}
}

// WaitReady polls the TCP port until the server accepts connections.
func (e *Engine) WaitReady(opts engine.Options, timeout func() bool) error {
	addr := fmt.Sprintf("127.0.0.1:%d", opts.Port)
	deadline := 60 * time.Second
	start := time.Now()
	for time.Since(start) < deadline {
		if timeout != nil && timeout() {
			return fmt.Errorf("timed out waiting for %s to become ready", addr)
		}
		conn, err := net.DialTimeout("tcp", addr, 500*time.Millisecond)
		if err == nil {
			conn.Close()
			return nil
		}
		time.Sleep(300 * time.Millisecond)
	}
	return fmt.Errorf("server did not become ready on %s within %s", addr, deadline)
}

// ShutdownArgs builds the mongosh shutdown command line (TCP): mongod
// performs a clean shutdown for the shutdown admin command; if this fails,
// the lifecycle escalates to SIGTERM (also graceful for mongod).
func (e *Engine) ShutdownArgs(opts engine.Options) []string {
	return []string{"--quiet", "--host", engine.ConnectHost(opts.BindAddress), "--port", fmt.Sprint(opts.Port),
		"--eval", "db.adminCommand({ shutdown: 1 })"}
}

// ClientArgs builds the interactive mongosh command line.
func (e *Engine) ClientArgs(opts engine.Options) []string {
	return []string{"--quiet", "--host", engine.ConnectHost(opts.BindAddress), "--port", fmt.Sprint(opts.Port)}
}

// ExecArgs builds the mongosh command line to run inline code.
func (e *Engine) ExecArgs(opts engine.Options, inlineSQL string) []string {
	args := e.ClientArgs(opts)
	if inlineSQL != "" {
		args = append(args, "--eval", inlineSQL)
	}
	return args
}

// Env: MongoDB distributions are self-contained.
func (e *Engine) Env(opts engine.Options) []string { return nil }

// SocketPath: connections are TCP-only; no unix socket.
func (e *Engine) SocketPath(opts engine.Options) string { return "" }

// WriteConfig renders mongod.conf into the datadir. Every writable
// location (dbPath, logs, pid) is pinned inside the instance datadir.
func (e *Engine) WriteConfig(opts engine.Options) (string, error) {
	root := opts.DataDir
	host := engine.ConnectHost(opts.BindAddress)

	for _, d := range []string{
		filepath.Join(root, "data"),
		filepath.Join(root, "log"),
		filepath.Join(root, "tmp"),
	} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return "", err
		}
	}

	conf := fmt.Sprintf(`# generated by dbpod — do not edit
storage:
  dbPath: %s
  directoryPerDB: false
net:
  port: %d
  bindIp: %s
  unixDomainSocket:
    enabled: false
systemLog:
  destination: file
  path: %s
  logAppend: true
processManagement:
  pidFilePath: %s
`, filepath.Join(root, "data"), opts.Port, host,
		filepath.Join(root, "log", "mongod.log"), filepath.Join(root, "dbpod.pid"))

	path := e.configPath(opts)
	if err := os.WriteFile(path, []byte(conf), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// configPath returns the mongod.conf path inside the datadir.
func (e *Engine) configPath(opts engine.Options) string {
	return filepath.Join(opts.DataDir, configFile)
}
